student_list = {'zakithikhDBN2022 - 4 April - Johannesburg Physical - seat 3',
            'ddhaalJHB2022 - 2 May - Cape Town Virtual',
            'thandohDBN2022 - 4 April - Phokeng Physical - seat 3',
            'zaneleJHB2022 - 2 May - Durban Virtual',
            'ntobekoDBN2022 - 4 April - Phokeng Physical - seat 2',
            'BusiJHB2022 - 2 May - Durban Virtual',
            'zinhlehDBN2022 - 4 April - Phokeng Physical - seat 1',
            'CebiJHB2022 - 2 May - Durban Virtual',
            'lukhona - 4 April - Phokeng Virtual',
            'ddhaalJHB2022 - 2 May - Durban Physical - seat 4',
            'gabiDBN2022 - 4 April - Phokeng Virtual',
            'ngakithilJHB2022 - 2 May - Durban Physical - seat 5',
            'zimthembilehDBN2022 - 4 April - Phokeng Virtual',
            'ngakuyelJHB2022 - 2 May - Durban Physical - seat 2',
            'zimlindilehDBN2022 - 4 April - Phokeng Virtual',
            'yenzileJHB2022 - 2 May - Durban Physical - seat 3',
            'zimthandilehDBN2022 - 4 April - Johannesburg Virtual',
            'kuhlengaweDBN2022 - 4 April - Durban Physical - seat 1',
            'zimkhonzileDBN2022 - 4 April - Johannesburg Virtual',
            'hlelokuhlehDBN2022 - 4 April - Durban Physical - seat 3',
            'zizonkehDBN2022 - 4 April - Johannesburg Virtual',
            'sibusisohDBN2022 - 4 April - Durban Physical - seat 2',
            'kholekileDBN2022 - 4 April - Johannesburg Virtual',
            'vusiDBN2022 - 4 April - Durban Physical - seat 9',
            'kholelwahDBN2022 - 4 April - Johannesburg Virtual',
            'zuzumuzihDBN2022 - 4 April - Durban Physical - seat 10',
            'thembelahDBN2022 - 4 April - Johannesburg Virtual',
            'babazileDBN2022 - 4 April - Durban Physical - seat 11',
            'thembisileDBN2022 - 4 April - Johannesburg Virtual',
            'owenkosiDBN2022 - 4 April - Durban Physical - seat 8',
            'thembisiweDBN2022 - 4 April - Johannesburg Physical - seat 5',
            'nobuhleJHB2022 - 2 May - Cape Town physical',
            'thenjisiweDBN2022 - 4 April - Johannesburg Physical - seat 6',
            'nonkonzoJHB2022 - 2 May - Cape Town Physical',
            'thethelelileDBN2022 - 4 April - Johannesburg Physical - seat 7',
            'nombusoJHB2022 - 2 May - Cape Town Virtual',
            'thembiDBN2022 - 4 April - Johannesburg Physical - seat 4',
            'nozizweJHB2022 - 2 May - Cape Town Virtual'}


for i in range(student_list):
    print(i)
